# Generated by Django 6.0.2 on 2026-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="CATEGORY",
            field=models.CharField(
                choices=[
                    ("M", "MOBILE"),
                    ("L", "LAPTOP"),
                    ("TW", "TOPWEAR"),
                    ("BW", "BOTTOMWEAR"),
                ],
                default="M",
                max_length=5,
            ),
        ),
    ]
